const actionType = {
    GETDATA_SUCCESS: 'GETDATA_SUCCESS',
    GETDATA_FAILURE: 'GETDATA_FAILURE',
    ADDUSER_SUCCESS: 'ADDUSER_SUCCESS',
    ADDUSER_FAILURE: 'ADDUSER_FAILURE',
    EDITUSER_SUCCESS: 'EDITUSER_SUCCESS',
    EDITUSER_FAILURE: 'EDITUSER_FAILURE'
}
export default actionType;